# Dependencies
markdown:         kramdown
rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Wildcraft
tagline:          'Blogs'
description:      'As Software Craftmen, We like it Natural & Wild'
url:              https://wildcraft.github.io/

author:           
  name:           'Narendran Solai'
  url:            https://twitter.com/narendran_ss

paginate:         1

# Custom vars
version:          2.0.0

github:           
  repo:           https://github.com/Wildcraft/

projects:
  first: https://github.com/orgs/Wildcraft/projects/1

force-https: True

google-tracking-id: "UA-105323889-1"

disqus-shortname: "http-wildcraft-github-io"

plugins:
  - jekyll-paginate
  - jemoji